import pygame


SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400

TILE_SIZE = 10
SCREEN_HORIZONTAL_TILES = SCREEN_WIDTH // TILE_SIZE
SCREEN_VERTICAL_TILES = SCREEN_HEIGHT // TILE_SIZE

BLACK = pygame.Color(0, 0, 0)
GREEN = pygame.Color(0, 255, 0)
RED = pygame.Color(255, 0, 0)  # not used yet
WHITE = pygame.Color(255, 255, 255)

SNAKE_START_SIZE = 3
SNAKE_SPEED = 15
SNAKE_START_X = 100
SNAKE_START_Y = 50
